# -*- mode: ruby -*-
# vi: set ft=ruby :

# Read SSH public keys from files
ssh_public_key_rsa = File.readlines('id_rsa.pub').first.strip
ssh_public_key_ed25519 = File.readlines('ed25519.pub').first.strip

# Configure vagrant boxes
Vagrant.configure("2") do |config|
  config.vm.box = "d-strobel/win2022sc"

  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p C:\\Users\\vagrant\\.ssh
    echo '#{ssh_public_key_rsa}' | Out-File -FilePath C:\\Users\\vagrant\\.ssh\\authorized_keys
    echo '#{ssh_public_key_ed25519}' | Out-File -FilePath C:\\Users\\vagrant\\.ssh\\authorized_keys -Append
  SHELL
end
